'use strict';
(() => {
  const cfg = window.APP_CONFIG || {};
  const project = cfg.project || {};
  const company = project.company || {};
  const orgId = project.organizationId || '';
  const root = document.getElementById('hub');
  const authReady = Boolean(cfg.supabaseUrl && cfg.supabaseAnonKey && !String(cfg.supabaseUrl).includes('INSERISCI_') && !String(cfg.supabaseAnonKey).includes('INSERISCI_') && window.supabase);
  const db = authReady ? window.supabase.createClient(cfg.supabaseUrl, cfg.supabaseAnonKey) : null;
  const easycomeBaseUrl = cfg.easycomeBaseUrl || project.identity?.easycomeBaseUrl || 'https://easy-come.it';
  const ownerUserId=project.identity?.ownerUserId||''; const ownerEmail=String(project.identity?.ownerEmail||company.email||'').toLowerCase();
  const accountAllowed=(user)=>!user?false:ownerUserId?user.id===ownerUserId:!ownerEmail||String(user.email||'').toLowerCase()===ownerEmail;
  const state = { session:null, tab:'home', requests:[], busy:false };
  const $=(q,r=document)=>r.querySelector(q); const $$=(q,r=document)=>[...r.querySelectorAll(q)];
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const uid=()=>globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2);
  const storage=localStorage;
  const identityEmail=()=>state.session?.user?.email||project.identity?.ownerEmail||company.email||'';
  const moduleName=(id)=>({crm:'Clienti e CRM',tasks:'Attività e scadenze',bookings:'Prenotazioni',appointments:'Appuntamenti',quotes:'Preventivi',orders:'Ordini',inventory:'Magazzino',invoices:'Fatture interne',payments:'Pagamenti',reports:'Report',automations:'Automazioni',multiuser:'Utenti e ruoli',website:'Sito pubblico',mobile_app:'App PWA',ai:'Assistente AI',documents:'Documenti',projects:'Progetti e commesse'}[id]||id.replace(/_/g,' '));
  function initials(){return String(company.name||'EC').split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase()}
  function localKey(){return `easycome-hub:${identityEmail()}:${orgId}`}
  function onboarding(){try{return JSON.parse(storage.getItem(localKey()+':onboarding')||'{}')}catch{return {}}}
  function saveOnboarding(value){storage.setItem(localKey()+':onboarding',JSON.stringify(value))}
  function toast(message,type='ok'){const n=document.createElement('div');n.className=`hub-toast ${type}`;n.textContent=message;document.body.appendChild(n);setTimeout(()=>n.remove(),2600)}

  async function loadRequests(){
    if(authReady&&state.session){
      const {data,error}=await db.from('easycome_support_requests').select('*').eq('user_id',state.session.user.id).order('created_at',{ascending:false}).limit(30);
      if(!error) state.requests=data||[];
      return;
    }
    try{state.requests=JSON.parse(storage.getItem(localKey()+':requests')||'[]')}catch{state.requests=[]}
  }

  async function createRequest(payload){
    const row={id:uid(),user_id:state.session?.user?.id||null,organization_id:orgId||null,company_name:company.name||'',customer_email:identityEmail(),kind:payload.kind,subject:payload.subject,description:payload.description,priority:payload.priority||'normal',status:'received',metadata:{project_version:project.version||'7.0.0',modules:project.modules||[]},created_at:new Date().toISOString()};
    if(authReady&&state.session){
      const {error}=await db.from('easycome_support_requests').insert(row); if(error) throw error;
    } else {state.requests.unshift(row);storage.setItem(localKey()+':requests',JSON.stringify(state.requests));}
    await loadRequests();
  }

  function auth(message=''){
    root.innerHTML=`<section class="hub-auth"><div class="hub-auth-story"><b>EC</b><span>SPAZIO RISERVATO EASY COME</span><h1>${esc(company.name||'Il tuo sistema')}</h1><p>Usa le stesse credenziali del tuo account Easy Come per aprire manuale, assistenza e nuove funzioni.</p></div><div class="hub-auth-panel"><form id="hubLogin"><h2>Accedi al tuo Hub</h2><p>${authReady?'Email e password sono le stesse usate su Easy Come.':'Configurazione cloud non collegata: puoi aprire una demo locale.'}</p>${message?`<div class="hub-alert">${esc(message)}</div>`:''}<label>Email<input name="email" type="email" required value="${esc(project.identity?.ownerEmail||company.email||'')}"></label><label>Password<input name="password" type="password" required minlength="8"></label><button type="submit">Accedi</button>${authReady?`<a href="${esc(easycomeBaseUrl)}" target="_blank" rel="noopener">Gestisci account su Easy Come</a>`:'<button type="button" id="hubDemo" class="secondary">Apri demo</button>'}</form></div></section>`;
    $('#hubDemo')?.addEventListener('click',()=>{state.session={user:{email:'demo@easycome.it'}};loadRequests().then(render)});
    $('#hubLogin').onsubmit=async(e)=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Accesso…';try{const values=Object.fromEntries(new FormData(e.currentTarget));if(!authReady){state.session={user:{email:values.email}};await loadRequests();render();return}const {data,error}=await db.auth.signInWithPassword(values);if(error)throw error;state.session=data.session;if(!accountAllowed(state.session?.user)){await db.auth.signOut();state.session=null;throw new Error('Questo Hub appartiene a un altro account Easy Come.')}await loadRequests();render()}catch(err){auth(err.message||String(err))}};
  }

  function sidebar(){return `<aside class="hub-sidebar"><div class="hub-logo"><b>EC</b><span><strong>Easy Come Hub</strong><small>${esc(company.name||'Azienda')}</small></span></div><nav>${[['home','⌂','Panoramica'],['manual','?','Manuale operativo'],['support','!','Assistenza'],['features','＋','Nuove funzioni'],['onboarding','✓','Avvio del sistema'],['updates','↻','Versioni e aggiornamenti']].map(([id,icon,label])=>`<button data-tab="${id}" class="${state.tab===id?'active':''}"><i>${icon}</i>${label}</button>`).join('')}</nav><footer><span>Connesso come</span><strong>${esc(identityEmail())}</strong><button id="hubLogout">Esci</button></footer></aside>`}
  function topbar(title,subtitle){return `<header class="hub-topbar"><div><span>SPAZIO EASY COME</span><h1>${esc(title)}</h1><p>${esc(subtitle)}</p></div><div class="hub-user"><b>${esc(initials())}</b><span><strong>${esc(company.name||'Azienda')}</strong><small>Versione ${esc(project.version||'7.0')}</small></span></div></header>`}

  function home(){const checks=onboarding();const completed=Object.values(checks).filter(Boolean).length;return `${topbar('Panoramica','Manuale, supporto e crescita del tuo sistema in un solo posto.')}<section class="hub-hero"><div><span>IL TUO SISTEMA EASY COME</span><h2>${esc(company.name||'La tua azienda')}</h2><p>${esc(company.description||'Il tuo gestionale è stato costruito sulle funzioni selezionate.')}</p></div><a href="manuale.html">Apri il manuale →</a></section><section class="hub-progress"><div><span>AVVIO DEL SISTEMA</span><strong>${completed} di 6 passaggi completati</strong><i><b style="width:${Math.round(completed/6*100)}%"></b></i></div><button data-go="onboarding">Continua configurazione</button></section><section class="hub-action-grid"><button data-go="manual"><b>?</b><span><strong>Manuale personalizzato</strong><small>Guida creata sulle tue funzioni</small></span></button><button data-go="support"><b>!</b><span><strong>Segnala un problema</strong><small>Descrivi cosa non funziona</small></span></button><button data-go="features"><b>＋</b><span><strong>Chiedi una funzione</strong><small>Valutazione e preventivo chiari</small></span></button><button data-request-kind="implementation"><b>↗</b><span><strong>Richiedi implementazione</strong><small>Database, deploy e collaudo</small></span></button></section><section class="hub-two"><article class="hub-card"><header><h3>Le tue richieste</h3><button data-go="support">Vedi tutte</button></header>${requestRows(4)}</article><article class="hub-card"><header><h3>Il tuo pacchetto</h3></header><div class="hub-module-pills">${(project.modules||[]).filter(id=>id!=='easycome_hub').slice(0,10).map(id=>`<span>${esc(moduleName(id))}</span>`).join('')}</div><a class="hub-link" href="easycome-project.json" download>Scarica configurazione tecnica</a></article></section>`}
  function requestRows(limit=30){const rows=state.requests.slice(0,limit);if(!rows.length)return '<div class="hub-empty"><b>Nessuna richiesta aperta</b><span>Quando ci scriverai, vedrai qui stato e risposte.</span></div>';return `<div class="hub-request-list">${rows.map(row=>`<article><div><strong>${esc(row.subject)}</strong><small>${esc(kindLabel(row.kind))} · ${new Date(row.created_at).toLocaleDateString('it-IT')}</small></div><span class="status ${esc(row.status)}">${esc(statusLabel(row.status))}</span></article>`).join('')}</div>`}
  function kindLabel(k){return {bug:'Problema tecnico',support:'Assistenza',feature:'Nuova funzione',implementation:'Implementazione',training:'Formazione',billing:'Amministrazione'}[k]||k}
  function statusLabel(s){return {received:'Ricevuta',reviewing:'In valutazione',planned:'Pianificata',answered:'Risposta inviata',closed:'Chiusa'}[s]||s}
  function manual(){return `${topbar('Manuale operativo','Una guida generata sulle sezioni e sui moduli del tuo gestionale.')}<section class="hub-manual-hero"><div><span>GUIDA PERSONALIZZATA</span><h2>Impara il sistema senza perderti.</h2><p>Primo accesso, dashboard, sezioni, backup, sicurezza ed Easy Come Hub.</p><div><a href="manuale.html">Apri manuale interattivo</a><a class="secondary" href="DOCUMENTI/MANUALE-OPERATIVO.pdf">Scarica PDF</a></div></div><b>?</b></section><section class="hub-card"><header><h3>Indice rapido</h3></header><div class="hub-index">${['Primo accesso con Easy Come ID','Dashboard e priorità','Creare e modificare record','Ricerca, filtri e viste','Excel, CSV e backup','Utenti, sicurezza e permessi','Richiedere assistenza o funzioni'].map((v,i)=>`<a href="manuale.html#${['inizio','panoramica','sezioni','sezioni','dati','sicurezza','hub'][i]}"><b>${String(i+1).padStart(2,'0')}</b><span>${v}</span></a>`).join('')}</div></section>`}
  function formView(kind){const feature=kind==='feature';return `${topbar(feature?'Nuove funzioni':'Assistenza Easy Come',feature?'Raccontaci cosa vuoi aggiungere: la richiesta resterà tracciata.':'Segnala un problema, chiedi aiuto o richiedi una configurazione.')}<section class="hub-form-layout"><form id="requestForm" class="hub-request-form"><label>Tipo di richiesta<select name="kind">${(feature?[['feature','Nuova funzione'],['implementation','Implementazione o integrazione'],['training','Formazione']]:[['bug','Qualcosa non funziona'],['support','Ho bisogno di aiuto'],['billing','Pagamento o documento'],['implementation','Richiedo implementazione']]).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Oggetto<input name="subject" required placeholder="Es. Collegare Google Calendar"></label><label>Descrizione<textarea name="description" required placeholder="Spiega cosa fai oggi, cosa vorresti ottenere e quando ti serve."></textarea></label><label>Priorità<select name="priority"><option value="normal">Normale</option><option value="high">Alta</option><option value="urgent">Bloccante</option></select></label><button type="submit">Invia richiesta a Easy Come</button><p>I dettagli vengono associati al tuo account e al gestionale ${esc(company.name||'')}.</p></form><aside class="hub-card"><h3>Richieste precedenti</h3>${requestRows()}</aside></section>`}
  function onboardingView(){const values=onboarding();const items=[['login','Accesso del titolare verificato'],['team','Collaboratori e ruoli definiti'],['data','Prime anagrafiche inserite'],['backup','Backup iniziale scaricato'],['mobile','Accesso da smartphone provato'],['manual','Manuale condiviso con il team']];return `${topbar('Avvio del sistema','Completa questi passaggi prima di lavorare con dati reali.')}<section class="hub-onboarding">${items.map(([id,label],index)=>`<label><input type="checkbox" data-onboarding="${id}" ${values[id]?'checked':''}><b>${String(index+1).padStart(2,'0')}</b><span><strong>${label}</strong><small>${['Usa lo stesso account Easy Come','Non condividere una sola password','Importa o crea i dati iniziali','Conserva una copia sicura','Installa la PWA se inclusa','Tutti devono sapere dove chiedere aiuto'][index]}</small></span></label>`).join('')}</section>`}
  function updates(){return `${topbar('Versioni e aggiornamenti','Tieni traccia di ciò che è incluso e delle prossime evoluzioni.')}<section class="hub-version"><div><span>VERSIONE INSTALLATA</span><strong>${esc(project.version||'7.0.0')}</strong><small>Generata ${project.generatedAt?new Date(project.generatedAt).toLocaleDateString('it-IT'):'per la tua azienda'}</small></div><article><h3>Stato del sistema</h3><p>Manuale e Easy Come Hub inclusi. Gli aggiornamenti personalizzati vengono valutati tramite richiesta funzione.</p><button data-go="features">Proponi un miglioramento</button></article></section><section class="hub-card"><header><h3>Componenti installati</h3></header><div class="hub-module-pills large">${(project.modules||[]).map(id=>`<span>${esc(moduleName(id))}</span>`).join('')}</div></section>`}

  function render(){root.innerHTML=`<div class="hub-shell">${sidebar()}<main class="hub-main">${state.tab==='home'?home():state.tab==='manual'?manual():state.tab==='support'?formView('support'):state.tab==='features'?formView('feature'):state.tab==='onboarding'?onboardingView():updates()}</main></div>`;bind()}
  function bind(){
    $$('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()});$$('[data-go]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.go;render()});
    $$('[data-request-kind]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.requestKind==='implementation'?'features':'support';render();setTimeout(()=>{const s=$('#requestForm select[name=kind]');if(s)s.value=b.dataset.requestKind},0)});
    $$('[data-onboarding]').forEach(c=>c.onchange=()=>{const values=onboarding();values[c.dataset.onboarding]=c.checked;saveOnboarding(values);render()});
    $('#requestForm')?.addEventListener('submit',async(e)=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;btn.textContent='Invio…';try{await createRequest(Object.fromEntries(new FormData(e.currentTarget)));toast('Richiesta inviata a Easy Come.');e.currentTarget.reset();render()}catch(err){toast(err.message||String(err),'error');btn.disabled=false;btn.textContent='Invia richiesta a Easy Come'}});
    $('#hubLogout')?.addEventListener('click',async()=>{if(authReady)await db.auth.signOut();state.session=null;auth()});
  }
  async function init(){if(authReady){const {data}=await db.auth.getSession();state.session=data.session;if(!state.session){auth();return}if(!accountAllowed(state.session.user)){await db.auth.signOut();state.session=null;auth('Questo Hub appartiene a un altro account Easy Come.');return}}else{auth();return}await loadRequests();render()}
  init();
})();
