(function () {
  'use strict';
  const gate = document.getElementById('accountGate');
  const shell = document.querySelector('.app-shell');
  const state = { client:null, session:null, config:null, ready:false, tab:'login' };
  const esc=(v)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const emit=()=>window.dispatchEvent(new CustomEvent('easycome:account-ready',{detail:{session:state.session,user:state.session?.user||null}}));

  function showShell() {
    gate.innerHTML=''; gate.classList.add('hidden'); shell?.classList.remove('account-pending');
    renderBadge(); emit();
  }
  function message(text,type='error'){const box=gate.querySelector('[data-account-message]');if(box){box.className=`account-message ${type}`;box.textContent=text||''}}
  function renderGate(note='') {
    shell?.classList.add('account-pending'); gate.classList.remove('hidden');
    gate.innerHTML=`<div class="account-gate"><section class="account-story"><a class="account-brand" href="/"><b>EC</b><span><strong>Easy Come</strong><small>Studio per imprese</small></span></a><div><span>UN SOLO ACCOUNT</span><h1>Costruisci oggi.<br>Accedi domani con le stesse credenziali.</h1><p>Il tuo account collega configuratore, acquisti, gestionale, manuale e Easy Come Hub.</p></div><div class="account-points"><span>✓ Progetti salvati online</span><span>✓ Accesso al gestionale acquistato</span><span>✓ Assistenza e nuove funzioni nello stesso spazio</span></div></section><section class="account-panel"><div class="account-card"><div class="account-tabs"><button data-account-tab="login" class="${state.tab==='login'?'active':''}">Accedi</button><button data-account-tab="signup" class="${state.tab==='signup'?'active':''}">Crea account</button></div><div data-account-message class="account-message ${note?'info':''}">${esc(note)}</div>${state.tab==='login'?loginForm():signupForm()}<small class="account-privacy">Continuando accetti <a href="/termini.html">Termini</a> e <a href="/privacy.html">Privacy</a>.</small></div></section></div>`;
    gate.querySelectorAll('[data-account-tab]').forEach(btn=>btn.onclick=()=>{state.tab=btn.dataset.accountTab;renderGate()});
    gate.querySelector('#accountLogin')?.addEventListener('submit',login);
    gate.querySelector('#accountSignup')?.addEventListener('submit',signup);
    gate.querySelector('#forgotPassword')?.addEventListener('click',forgot);
  }
  function loginForm(){return `<form id="accountLogin" class="account-form"><div><span>Il tuo spazio Easy Come</span><h2>Bentornato.</h2><p>Usa le stesse credenziali che userai nel tuo gestionale.</p></div><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Password<input name="password" type="password" required minlength="8" autocomplete="current-password"></label><button type="submit">Accedi e continua</button><button id="forgotPassword" type="button" class="account-link">Password dimenticata?</button></form>`}
  function signupForm(){return `<form id="accountSignup" class="account-form"><div><span>Il tuo account centrale</span><h2>Partiamo da te.</h2><p>Crealo una volta: resterà valido per sito, gestionale e Hub.</p></div><div class="account-two"><label>Nome e cognome<input name="fullName" required autocomplete="name"></label><label>Nome attività<input name="companyName" required autocomplete="organization"></label></div><label>Email<input name="email" type="email" required autocomplete="email"></label><label>Password<input name="password" type="password" required minlength="8" autocomplete="new-password"><small>Almeno 8 caratteri.</small></label><button type="submit">Crea account gratuito</button></form>`}
  function busy(form,on,label){const b=form.querySelector('button[type="submit"]');if(!b)return;b.disabled=on;if(on){b.dataset.old=b.textContent;b.textContent=label}else b.textContent=b.dataset.old||'Continua'}
  async function login(e){e.preventDefault();const form=e.currentTarget;busy(form,true,'Accesso…');try{const v=Object.fromEntries(new FormData(form));const {data,error}=await state.client.auth.signInWithPassword({email:v.email,password:v.password});if(error)throw error;state.session=data.session;showShell()}catch(err){message(err.message||String(err))}finally{busy(form,false)}}
  async function signup(e){e.preventDefault();const form=e.currentTarget;busy(form,true,'Creazione account…');try{const v=Object.fromEntries(new FormData(form));const {data,error}=await state.client.auth.signUp({email:v.email,password:v.password,options:{data:{full_name:v.fullName,company_name:v.companyName},emailRedirectTo:location.origin}});if(error)throw error;if(data.session){state.session=data.session;showShell()}else{state.tab='login';renderGate('Account creato. Controlla la tua email per confermarlo, poi accedi.')}}catch(err){message(err.message||String(err))}finally{busy(form,false)}}
  async function forgot(){const email=gate.querySelector('input[name="email"]')?.value?.trim();if(!email){message('Inserisci prima la tua email.');return}const {error}=await state.client.auth.resetPasswordForEmail(email,{redirectTo:location.origin});message(error?error.message:'Ti abbiamo inviato il link per reimpostare la password.',error?'error':'success')}
  function renderBadge(){const host=document.querySelector('.workspace-top');if(!host||!state.session)return;let el=document.getElementById('accountBadge');if(!el){el=document.createElement('div');el.id='accountBadge';el.className='account-badge';host.appendChild(el)}const email=state.session.user.email||'';const name=state.session.user.user_metadata?.full_name||email.split('@')[0];el.innerHTML=`<button id="accountMenu"><b>${esc(name.slice(0,1).toUpperCase())}</b><span><strong>${esc(name)}</strong><small>${esc(email)}</small></span></button><div class="account-menu hidden"><a href="#" id="myProjects">Il mio progetto</a><button id="accountLogout">Esci</button></div>`;el.querySelector('#accountMenu').onclick=()=>el.querySelector('.account-menu').classList.toggle('hidden');el.querySelector('#accountLogout').onclick=async()=>{await state.client.auth.signOut();state.session=null;state.tab='login';renderGate()};}
  async function accessToken(){if(!state.client)return'';const {data}=await state.client.auth.getSession();state.session=data.session;return data.session?.access_token||''}
  async function saveProject(project){if(!state.client||!state.session)return;const payload={user_id:state.session.user.id,name:project.company?.name||'Nuovo progetto',project,updated_at:new Date().toISOString()};const {error}=await state.client.from('easycome_projects').upsert(payload,{onConflict:'user_id'});if(error)console.warn('Salvataggio cloud:',error.message)}
  async function loadLatestProject(){if(!state.client||!state.session)return null;const {data,error}=await state.client.from('easycome_projects').select('project').eq('user_id',state.session.user.id).maybeSingle();if(error){console.warn(error.message);return null}return data?.project||null}
  async function init(){try{const response=await fetch('/api/public-config',{cache:'no-store'});if(!response.ok)throw new Error((await response.json()).error||'Configurazione account non disponibile.');state.config=await response.json();if(!window.supabase)throw new Error('Libreria account non caricata.');state.client=window.supabase.createClient(state.config.supabaseUrl,state.config.supabaseAnonKey);const {data}=await state.client.auth.getSession();state.session=data.session;state.client.auth.onAuthStateChange((_event,session)=>{state.session=session;if(session)showShell();else if(state.ready)renderGate()});state.ready=true;if(state.session)showShell();else renderGate()}catch(err){shell?.classList.add('account-pending');renderGate();message(`${err.message} Inserisci SUPABASE_ANON_KEY su Vercel.`)}}
  window.EasyComeAccount={getSession:()=>state.session,getAccessToken:accessToken,saveProject,loadLatestProject,getUser:()=>state.session?.user||null,getClient:()=>state.client};
  init();
})();
