(function(){
'use strict';
const G=window.ECGenerator;
const SALES=window.EASYCOME_SALES||{mode:'customer',checkoutEndpoint:'/api/create-checkout-session',termsUrl:'/termini',privacyUrl:'/privacy'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v||0));
const DEMO_SLUG=new URLSearchParams(location.search).get('demo')||'';

const STEPS=[
  {label:'La struttura',sub:'4 informazioni'},
  {label:'Cosa ti serve',sub:'Scegli per obiettivi'},
  {label:'Il tuo gestionale',sub:'Guarda l’anteprima'},
  {label:'Prezzo',sub:'Tutto chiaro prima di pagare'}
];
const FEATURES=[
  {id:'audit',title:'Evitare errori e dimenticanze',name:'Controllo',k:'PIÙ CONTROLLO',desc:'Easy Come evidenzia saldi aperti, dati mancanti e situazioni da verificare.'},
  {id:'finance',title:'Capire come sta andando la struttura',name:'Finance',k:'NUMERI CHIARI',desc:'Occupazione, ADR, RevPAR, ricavi, costi e incassi in una vista semplice.'},
  {id:'channel_sync',title:'Tenere ordinati i calendari dei canali',name:'Canali e calendari',k:'MENO CAOS',desc:'Un punto unico per gestire la disponibilità proveniente dai canali che utilizzi.'},
  {ids:['guest_comms','self_checkin'],title:'Semplificare arrivi e comunicazioni',name:'Accoglienza ospiti',k:'OSPITI',desc:'Messaggi, dati pre-arrivo e checklist per preparare il soggiorno.'},
  {id:'tourist_tax',title:'Tenere sotto controllo la tassa di soggiorno',name:'Tassa di soggiorno',k:'ADEMPIMENTI',desc:'Importi, esenzioni e stato restano collegati al soggiorno.'},
  {id:'automations',title:'Ridurre le attività ripetitive',name:'Automazioni',k:'TEMPO',desc:'Easy Come prepara o esegue le routine configurate su arrivi, partenze, pagamenti e pulizie.'}
];
const CORE=['Oggi','Calendario','Prenotazioni','Ospiti','Camere / alloggi','Pagamenti','Pulizie','Dashboard','Hub'];
let activeUserId='guest', currentStep=0, previewTab='today';
let project=normalize(G.defaultProject());

function normalize(input){
  const base=G.defaultProject();
  const p={...base,...(input||{}),company:{...base.company,...(input?.company||{})},pricing:{...base.pricing,...(input?.pricing||{})},delivery:{...base.delivery,...(input?.delivery||{})}};
  const allowed=new Set(['hospitality_core','reports','easycome_hub',...FEATURES.flatMap(featureIds)]);
  p.modules=Array.from(new Set([...(p.modules||[]).filter(id=>allowed.has(id)),'hospitality_core','reports','easycome_hub']));
  p.customEntities=[];p.automations=Array.isArray(p.automations)?p.automations:[];
  p.hub={enabled:true,manual:true,support:true,featureRequests:true,onboarding:true,...(p.hub||{})};
  const h=p.hospitality||{};
  const count=Math.max(1,Number(h.unitCount||h.unitTypes?.reduce((s,u)=>s+Number(u.count||1),0)||4));
  p.hospitality={...h,type:h.type||'B&B',city:h.city||'',unitCount:count,maxGuests:Math.max(2,count*2),checkinFrom:h.checkinFrom||'15:00',checkoutBy:h.checkoutBy||'10:30',cancellationPolicy:h.cancellationPolicy||'Da definire in implementazione',unitTypes:[{name:'Camera / alloggio',count,capacity:2,basePrice:Number(h.unitTypes?.[0]?.basePrice||95)}]};
  p.templateId='hospitality';p.company.industry='Ospitalità indipendente';
  p.delivery.implementationSelected=true;p.delivery.implementationPrice=150;p.delivery.managedServiceSelected=false;p.delivery.managedServicePrice=0;
  syncProject(p);return p;
}
function syncProject(p=project){
  const h=p.hospitality||{};const count=Math.max(1,Number(h.unitCount||1));
  h.unitTypes=[{name:'Camera / alloggio',count,capacity:2,basePrice:Number(h.unitTypes?.[0]?.basePrice||95)}];h.maxGuests=Math.max(2,count*2);
  p.company.description=`Gestionale Easy Come Hospitality per ${h.type||'struttura ricettiva'} con ${count} camere o alloggi. Gestione di prenotazioni, ospiti, camere, pagamenti, pulizie e attività operative.`;
  p.pricing.mode='none';p.pricing.enabled=false;
  p.delivery.implementationSelected=true;p.delivery.implementationPrice=150;p.delivery.managedServiceSelected=false;p.delivery.managedServicePrice=0;
}
function featureIds(f){return f.ids||[f.id]}
function modulePrice(id){return Number(G.MODULES.find(m=>m.id===id)?.price||0)}
function featurePrice(f){return featureIds(f).reduce((s,id)=>s+modulePrice(id),0)}
function featureActive(f){return featureIds(f).every(id=>project.modules.includes(id))}
function selectedFeatures(){return FEATURES.filter(featureActive)}
function setFeature(f,on){featureIds(f).forEach(id=>{project.modules=project.modules.filter(x=>x!==id);if(on)project.modules.push(id)});project.modules=Array.from(new Set(project.modules));project.delivery.previewApproved=false;save();render()}
function draftKey(){return `easycome-hospitality-config:${activeUserId||'guest'}`}
function save(){syncProject();try{localStorage.setItem(draftKey(),JSON.stringify(project))}catch(_){}window.EasyComeAccount?.saveProject?.(project)}
function localDraft(){try{return JSON.parse(localStorage.getItem(draftKey())||'null')}catch(_){return null}}
function toast(text){const n=document.createElement('div');n.className='toast';n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),1900)}

function render(){syncProject();renderSteps();renderPanel();renderSummary();updateNav();save()}
function renderSteps(){const root=$('#stepList');if(!root)return;root.innerHTML=STEPS.map((s,i)=>`<button class="step-item ${i===currentStep?'active':''}" data-step="${i}"><span class="step-number">${String(i+1).padStart(2,'0')}</span><span><strong>${s.label}</strong><small>${s.sub}</small></span></button>`).join('');$$('[data-step]',root).forEach(b=>b.onclick=()=>{const target=Number(b.dataset.step);if(target<currentStep){currentStep=target;render();scrollTo(0,0)}})}
function heading(k,title,desc){return `<div class="panel-heading"><div><span class="eyebrow">${k}</span><h1>${title}</h1><p>${desc}</p></div><div class="step-badge">${currentStep+1} di ${STEPS.length}</div></div>`}
function renderPanel(){const fn=[stepStructure,stepNeeds,stepPreview,stepPrice][currentStep];$('#panel').innerHTML=fn();bindCurrent()}

function stepStructure(){const h=project.hospitality,c=project.company;return `${heading('1 · LA TUA STRUTTURA','Partiamo dalle cose semplici.','Quattro informazioni. Il resto lo configuriamo noi durante l’implementazione.')}
<div class="section-label"><div><h2>Che struttura gestisci?</h2></div><p>Scegli quella più vicina.</p></div>
<div class="quick-choice">${['B&B','Affittacamere','Casa vacanza'].map(v=>`<button data-type="${v}" class="${h.type===v?'active':''}"><b>${v}</b><small>${v==='B&B'?'Camere e ospitalità':v==='Affittacamere'?'Camere o unità indipendenti':'Case o appartamenti'}</small></button>`).join('')}</div>
<div class="simple-grid"><label class="field"><span>Nome della struttura</span><input id="companyName" value="${esc(c.name||'')}" placeholder="Es. Dimora Aurora" autofocus></label><label class="field"><span>Città</span><input id="city" value="${esc(h.city||'')}" placeholder="Es. Roma"></label><label class="field"><span>Quante camere / alloggi gestisci?</span><input id="unitCount" type="number" min="1" max="100" value="${Number(h.unitCount||1)}"></label><label class="field"><span>La tua email</span><input id="companyEmail" type="email" value="${esc(c.email||'')}" placeholder="nome@email.it"><small>Ti servirà per l’accesso dopo l’acquisto.</small></label></div>
<div class="preview-note"><b>Non ti chiediamo altro adesso.</b><p>Tipologie camere, tariffe, orari, utenti, regole e import iniziali vengono definiti con te nell’implementazione obbligatoria.</p></div>`}

function stepNeeds(){const selected=selectedFeatures();return `${heading('2 · COSA TI SERVE','Cosa vuoi rendere più semplice?','Non devi conoscere i moduli. Leggi il risultato che vuoi ottenere e attiva solo ciò che ti interessa.')}
<section class="included"><span>IL GESTIONALE È GIÀ COMPLETO</span><h2>La gestione quotidiana è inclusa.</h2><p>Oggi, calendario, prenotazioni, ospiti, camere, pagamenti, pulizie e Hub fanno parte del pacchetto base.</p><div class="core-pills">${CORE.map(x=>`<i>${x}</i>`).join('')}</div></section>
<div class="section-label"><div><h2>Vuoi aggiungere qualcosa?</h2></div><p>${selected.length?`${selected.length} scelte attive`:'Puoi anche continuare senza extra.'}</p></div>
<div class="feature-grid">${FEATURES.map((f,i)=>`<button class="feature-card ${featureActive(f)?'active':''}" data-feature="${i}"><div><span>${f.k}</span><h3>${f.title}</h3><p>${f.desc}</p><span class="feature-price">${featurePrice(f)?'+'+money(featurePrice(f)):'Incluso'}</span></div><div class="toggle"><i></i></div></button>`).join('')}</div>
<div class="preview-note"><b>Non sai cosa scegliere?</b><p>Lascia tutto com’è. Durante l’implementazione verifichiamo insieme se manca qualcosa prima di consegnare il gestionale.</p></div>`}

function previewToday(){const n=Number(project.hospitality.unitCount||1),occ=Math.min(n,Math.max(1,Math.round(n*.68))),pct=Math.round(occ/n*100);return `<small>OGGI · ESEMPIO</small><h2>${esc(project.company.name||'La tua struttura')}</h2><p>La prima schermata ti dice cosa richiede attenzione, senza farti cercare tra le sezioni.</p><div class="pv-kpis"><div><span>Occupazione</span><strong>${pct}%</strong></div><div><span>Arrivi</span><strong>3</strong></div><div><span>Partenze</span><strong>2</strong></div><div><span>Da incassare</span><strong>€640</strong></div></div><div class="pv-list"><div class="pv-row"><b>15:00</b><div><strong>Giulia Romano</strong><small>Camera 2 · 2 ospiti · saldo €190</small></div><em>ARRIVO</em></div><div class="pv-row"><b>10:30</b><div><strong>Marco De Luca</strong><small>Camera 4 · soggiorno da chiudere</small></div><em>PARTENZA</em></div><div class="pv-row"><b>ORA</b><div><strong>Camera 4</strong><small>Pulizia da completare prima del prossimo arrivo</small></div><em>PRIORITÀ</em></div></div>`}
function previewCalendar(){return `<small>CALENDARIO · ESEMPIO</small><h2>Tutte le prenotazioni, a colpo d’occhio.</h2><p>Ogni soggiorno collega ospite, alloggio, stato, importo e canale.</p><div class="pv-list" style="margin-top:18px"><div class="pv-row"><b>12–15</b><div><strong>Camera 1 · Anna Klein</strong><small>3 notti · Confermata</small></div><em>DIRETTA</em></div><div class="pv-row"><b>13–17</b><div><strong>Camera 2 · Luca Ferri</strong><small>4 notti · Confermata</small></div><em>PORTALE</em></div><div class="pv-row"><b>16–20</b><div><strong>Camera 3 · Sara Conti</strong><small>4 notti · Caparra registrata</small></div><em>DIRETTA</em></div></div>`}
function previewControl(){return `<small>CONTROLLO · ESEMPIO</small><h2>Easy Come ti mostra cosa verificare.</h2><p>Non devi controllare tutto a mano. Parti dalle eccezioni.</p><div class="pv-list" style="margin-top:18px"><div class="pv-row"><b>ALTA</b><div><strong>Saldo ancora aperto</strong><small>Prenotazione EC-184 · €190 da verificare</small></div><em>VERIFICA</em></div><div class="pv-row"><b>MEDIA</b><div><strong>Dati ospite incompleti</strong><small>Arrivo previsto oggi alle 17:00</small></div><em>APERTA</em></div></div>`}
function previewFinance(){return `<small>FINANCE · ESEMPIO</small><h2>I numeri della struttura diventano leggibili.</h2><p>Gli indicatori arrivano dagli stessi dati che usi ogni giorno.</p><div class="pv-kpis"><div><span>Occupazione</span><strong>74%</strong></div><div><span>ADR</span><strong>€118</strong></div><div><span>RevPAR</span><strong>€87</strong></div><div><span>Ricavi mese</span><strong>€12,4k</strong></div></div><div class="preview-note"><b>Non è contabilità fiscale.</b><p>È controllo gestionale: serve a capire andamento, incassi, costi e performance della struttura.</p></div>`}
function stepPreview(){const tabs=[['today','Oggi'],['calendar','Calendario']];if(project.modules.includes('audit'))tabs.push(['control','Controllo']);if(project.modules.includes('finance'))tabs.push(['finance','Finance']);if(!tabs.some(t=>t[0]===previewTab))previewTab='today';const body=previewTab==='calendar'?previewCalendar():previewTab==='control'?previewControl():previewTab==='finance'?previewFinance():previewToday();return `${heading('3 · IL TUO GESTIONALE','Guarda cosa stai configurando.','Questa non è la configurazione tecnica finale: è un’anteprima del modo in cui lavorerai con Easy Come.')}
<div class="preview-shell"><div class="preview-bar"><span>ANTEPRIMA EASY COME HOSPITALITY</span><span>${esc(project.hospitality.type)} · ${Number(project.hospitality.unitCount||1)} alloggi</span></div><div class="preview-body"><aside class="preview-nav"><b>Easy Come</b>${['Oggi','Calendario','Prenotazioni','Ospiti','Camere','Pagamenti','Pulizie',...(project.modules.includes('audit')?['Controllo']:[]),...(project.modules.includes('finance')?['Finance']:[]),'Hub'].map(x=>`<span class="${x.toLowerCase()===({today:'oggi',calendar:'calendario',control:'controllo',finance:'finance'}[previewTab]||'')?'active':''}">${x}</span>`).join('')}</aside><main class="preview-main"><div class="quick-choice" style="grid-template-columns:repeat(${tabs.length},1fr);margin-bottom:18px">${tabs.map(([id,l])=>`<button data-preview-tab="${id}" class="${previewTab===id?'active':''}"><b>${l}</b></button>`).join('')}</div>${body}</main></div></div>
<div class="preview-note"><b>Dopo l’acquisto lo adattiamo davvero alla tua struttura.</b><p>Camere, nomi, tariffe, regole, utenti e dati iniziali vengono configurati nell’implementazione da €150.</p></div>`}

function stepPrice(){const price=G.calculatePrice(project), selected=selectedFeatures();return `${heading('4 · PREZZO','Sai esattamente cosa compri.','Un solo pagamento per il pacchetto scelto. L’implementazione è obbligatoria perché è il momento in cui Easy Come viene adattato alla tua struttura.')}
<section class="price-card"><span>IL TUO EASY COME HOSPITALITY</span><h2>${esc(project.company.name||'La tua struttura')}</h2><div class="price-line"><span>Gestionale Hospitality</span><strong>${money(price.base)}</strong></div>${price.extras?`<div class="price-line"><span>Funzioni aggiunte</span><strong>${money(price.extras)}</strong></div>`:''}<div class="price-line"><span>Implementazione obbligatoria</span><strong>${money(price.implementation)}</strong></div><div class="price-total"><div><small>TOTALE UNA TANTUM</small><span style="display:block;margin-top:4px;color:#ffffff9a">Nessun canone Easy Come obbligatorio</span></div><strong>${money(price.total)}</strong></div><div class="package-list">${CORE.slice(0,7).map(x=>`<div>${x}</div>`).join('')}${selected.map(f=>`<div>${f.name}</div>`).join('')}</div></section>
<section class="buy-card"><span class="eyebrow">DOPO L’ACQUISTO</span><h3>Noi completiamo la parte difficile.</h3><p><b>1.</b> Definiamo camere/alloggi e regole reali. &nbsp; <b>2.</b> Configuriamo utenti e dati iniziali. &nbsp; <b>3.</b> Testiamo il flusso operativo. &nbsp; <b>4.</b> Ti consegniamo il gestionale pronto.</p><button id="buy" class="primary-action">Acquista il pacchetto · ${money(price.total)}</button><button id="backPreview" class="secondary-action">Rivedi l’anteprima</button></section>`}

function renderSummary(){const h=project.hospitality,selected=selectedFeatures(),price=G.calculatePrice(project);$('#summary').innerHTML=`<span>LA TUA CONFIGURAZIONE</span><h2>${esc(project.company.name||'Nuova struttura')}</h2><div class="type">${esc(h.type)} · ${Number(h.unitCount||1)} alloggi</div><div class="summary-block"><small>GESTIONE INCLUSA</small>${['Prenotazioni','Ospiti','Camere / alloggi','Pagamenti','Pulizie','Hub'].map(x=>`<div class="summary-feature"><span>${x}</span><b>Incluso</b></div>`).join('')}</div>${selected.length?`<div class="summary-block"><small>HAI AGGIUNTO</small>${selected.map(f=>`<div class="summary-feature"><span>${f.name}</span><b>+${money(featurePrice(f))}</b></div>`).join('')}</div>`:`<div class="summary-block"><small>EXTRA</small><div class="summary-feature"><span>Nessun extra selezionato</span><b>Base</b></div></div>`}<div class="summary-price"><small>Totale · implementazione inclusa</small><strong>${money(price.total)}</strong></div>`}
function updateNav(){const prev=$('#previous'),next=$('#next');prev.disabled=currentStep===0;next.textContent=currentStep===STEPS.length-1?'Torna all’inizio':currentStep===STEPS.length-2?'Vedi il prezzo':'Continua';$('#progressMobile').textContent=`${currentStep+1} di ${STEPS.length}`}
function bind(id,fn){const el=$('#'+id);if(!el)return;el.oninput=()=>{fn(el.value);project.delivery.previewApproved=false;save();renderSummary()}}
function bindCurrent(){
  if(currentStep===0){$$('[data-type]').forEach(b=>b.onclick=()=>{project.hospitality.type=b.dataset.type;project.delivery.previewApproved=false;render()});bind('companyName',v=>{project.company.name=v;project.company.slug=G.slugify(v)});bind('city',v=>project.hospitality.city=v);bind('companyEmail',v=>project.company.email=v);bind('unitCount',v=>project.hospitality.unitCount=Math.max(1,Number(v||1)))}
  if(currentStep===1){$$('[data-feature]').forEach(b=>b.onclick=()=>{const f=FEATURES[Number(b.dataset.feature)];setFeature(f,!featureActive(f))})}
  if(currentStep===2){$$('[data-preview-tab]').forEach(x=>x.onclick=()=>{previewTab=x.dataset.previewTab;render()})}
  if(currentStep===3){$('#backPreview')?.addEventListener('click',()=>{currentStep=2;render();scrollTo(0,0)});$('#buy')?.addEventListener('click',openCheckout)}
}
function validate(){if(currentStep===0){if(String(project.company.name||'').trim().length<3){toast('Inserisci il nome della struttura.');return false}if(!String(project.hospitality.city||'').trim()){toast('Inserisci la città.');return false}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(project.company.email||''))){toast('Inserisci un’email valida.');return false}}return true}
function next(){if(currentStep===STEPS.length-1){currentStep=0;project.delivery.previewApproved=false;render();scrollTo(0,0);return}if(!validate())return;if(currentStep===2)project.delivery.previewApproved=true;currentStep++;render();scrollTo(0,0)}
function prev(){if(currentStep>0){currentStep--;render();scrollTo(0,0)}}

function projectForCheckout(){syncProject();return {...project,company:{...project.company},delivery:{...project.delivery,previewApproved:true,implementationSelected:true,implementationPrice:150,managedServiceSelected:false,managedServicePrice:0}}}
function openCheckout(){project.delivery.previewApproved=true;syncProject();save();const price=G.calculatePrice(project),audit=G.auditProject(project);if(!audit.ready){toast(audit.blockers[0]||'Completa prima la configurazione.');return}const root=$('#checkoutRoot');root.innerHTML=`<div class="checkout-overlay"><section class="checkout-sheet"><div class="checkout-copy"><div class="checkout-top"><div><span class="checkout-label">ORDINE EASY COME</span><h2>${esc(project.company.name)}</h2><p>Un ultimo controllo prima del pagamento.</p></div><button class="checkout-close" id="closeCheckout">×</button></div><div class="order-lines"><div><span>Gestionale Hospitality</span><strong>${money(price.base)}</strong></div>${price.extras?`<div><span>Funzioni aggiunte</span><strong>${money(price.extras)}</strong></div>`:''}<div><span>Implementazione obbligatoria</span><strong>${money(price.implementation)}</strong></div></div><div class="order-total"><div><span class="checkout-label">TOTALE UNA TANTUM</span><small>Nessun canone Easy Come</small></div><strong>${money(price.total)}</strong></div></div><div class="checkout-form-wrap"><form id="checkoutForm"><span class="eyebrow">DATI ORDINE</span><h3>A chi intestiamo il progetto?</h3><p>Se non hai ancora un account, te lo chiederemo prima di aprire il pagamento.</p><div class="simple-grid"><label class="field"><span>Nome e cognome</span><input name="customerName" required></label><label class="field"><span>Email</span><input name="email" type="email" required value="${esc(project.company.email||'')}"></label><label class="field"><span>Telefono</span><input name="phone"></label><label class="field"><span>Partita IVA / CF</span><input name="taxId"></label><label class="field full"><span>Struttura / ragione sociale</span><input name="companyName" required value="${esc(project.company.name||'')}"></label></div><label class="legal-check"><input type="checkbox" name="terms" required><span>Accetto i <a href="${esc(SALES.termsUrl||'/termini')}" target="_blank">Termini e condizioni</a> e ho letto la <a href="${esc(SALES.privacyUrl||'/privacy')}" target="_blank">Privacy Policy</a>.</span></label><label class="legal-check"><input type="checkbox" name="immediatePerformance" required><span>Chiedo che l’implementazione prevista inizi dopo il pagamento.</span></label><div id="checkoutError"></div><button id="payButton" class="primary-action" type="submit">Continua al pagamento · ${money(price.total)}</button><div class="secure-row">Pagamento gestito tramite Stripe.</div></form></div></section></div>`;$('#closeCheckout').onclick=()=>root.innerHTML='';$('#checkoutForm').onsubmit=submitCheckout}
async function submitCheckout(e){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const customer=Object.fromEntries(new FormData(form)),button=$('#payButton'),error=$('#checkoutError');button.disabled=true;button.textContent='Controllo account…';error.innerHTML='';try{const token=await window.EasyComeAccount?.getAccessToken?.();if(!token){save();const next=encodeURIComponent('/studio.html');location.href=`/accedi.html?mode=login&next=${next}`;return}button.textContent='Apertura del pagamento…';const response=await fetch(SALES.checkoutEndpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({project:projectForCheckout(),customer,legal:{termsAccepted:customer.terms==='on',immediatePerformance:customer.immediatePerformance==='on',termsVersion:'EC-TOS-HOSPITALITY-V1.2',acceptedAt:new Date().toISOString()},sourceUrl:location.href})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.url)throw new Error(data.error||'Impossibile avviare il pagamento.');location.href=data.url}catch(err){error.innerHTML=`<div class="checkout-error">${esc(err.message||String(err))}</div>`;button.disabled=false;button.textContent=`Continua al pagamento · ${money(G.calculatePrice(project).total)}`}}

async function loadDemo(){if(!DEMO_SLUG)return null;try{const r=await fetch(`/api/demo-public?slug=${encodeURIComponent(DEMO_SLUG)}`,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.project)return null;const p=d.project;p.company={...(p.company||{}),email:''};p.delivery={...(p.delivery||{}),previewApproved:false};return p}catch(_){return null}}
async function initialize(user){activeUserId=user?.id||'guest';const demo=await loadDemo();const cloud=demo?null:await window.EasyComeAccount?.loadLatestProject?.();const local=demo?null:localDraft();project=normalize(demo||cloud||local||G.defaultProject());if(!project.company.email&&user?.email)project.company.email=user.email;currentStep=demo?1:0;document.querySelector('.app-shell')?.classList.remove('account-pending');render()}
window.addEventListener('easycome:account-ready',e=>initialize(e.detail?.user));
$('#previous').onclick=prev;$('#next').onclick=next;$('#homeLink').onclick=()=>location.href='index.html';
setTimeout(()=>{if(document.querySelector('.app-shell')?.classList.contains('account-pending')){document.querySelector('.app-shell')?.classList.remove('account-pending');render()}},900);
})();
