(function(){
'use strict';
const G=window.ECGenerator,T=window.ECHospitalityTemplates,SALES=window.EASYCOME_SALES||{};
if(!G||!T){document.body.innerHTML='<div style="padding:40px;font:18px Arial">Easy Come non è stato caricato correttamente.</div>';return}
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',minimumFractionDigits:0,maximumFractionDigits:2}).format(Number(v||0));
const DEMO_SLUG=new URLSearchParams(location.search).get('demo')||'';
const DEMO_MODE=Boolean(DEMO_SLUG||window.EASYCOME_PREFILL_DEMO);
const STANDARD_BASE=183, STANDARD_MODULES=['hospitality_core','reports','audit','easycome_hub'];
const ADDONS=[
 {id:'channel',title:'Calendari dei portali',desc:'Import/export calendari e centro canali per ridurre sovrapposizioni.',modules:['channel_sync']},
 {id:'finance',title:'Costi e margini',desc:'Aggiunge costi, fornitori, margine gestionale e lettura economica ai Numeri.',modules:['expenses','finance']},
 {id:'guest',title:'Pre-arrivo e messaggi',desc:'Raccogli dati prima dell’arrivo e prepara comunicazioni del soggiorno.',modules:['guest_comms','self_checkin']},
 {id:'tax',title:'Tassa di soggiorno',desc:'Importi, esenzioni e stato collegati direttamente alla prenotazione.',modules:['tourist_tax']},
 {id:'pricing',title:'Tariffe e regole',desc:'Stagioni, durata, promozioni e regole tariffarie configurabili.',modules:['dynamic_pricing']},
 {id:'team',title:'Team e permessi',desc:'Accessi separati per titolare, reception, pulizie e collaboratori.',modules:['multiuser']},
 {id:'auto',title:'Automazioni operative',desc:'Trigger su prenotazioni, arrivi, partenze, pagamenti e pulizie.',modules:['automations']}
];
let project=null,previewMode='desktop',demoPayload=null;
function normalize(p){p=p||G.defaultProject();p.version='8.0.0-hospitality-factory-first';p.templateId='hospitality';p.company={...G.defaultProject().company,...(p.company||{})};p.hospitality={...G.defaultProject().hospitality,...(p.hospitality||{})};p.delivery={...G.defaultProject().delivery,...(p.delivery||{}),packagePrice:STANDARD_BASE,implementationSelected:true,implementationPrice:150,managedServiceSelected:false,managedServicePrice:0};p.modules=[...new Set([...(p.modules||[]),...STANDARD_MODULES])];p.modules=p.modules.filter(id=>STANDARD_MODULES.includes(id)||ADDONS.some(a=>a.modules.includes(id)));p.pricing={...G.defaultProject().pricing,...(p.pricing||{})};return p}
function localDraft(){try{return JSON.parse(localStorage.getItem('easycome_hospitality_v8')||'null')}catch(_){return null}}
function save(){try{localStorage.setItem('easycome_hospitality_v8',JSON.stringify(project))}catch(_){}window.EasyComeAccount?.saveProject?.(project).catch?.(()=>{})}
function selectedAddon(a){return a.modules.every(m=>project.modules.includes(m))}
function modulePrice(id){return Number((G.MODULES||[]).find(m=>m.id===id)?.price||0)}
function addonListPrice(a){return a.modules.reduce((s,m)=>s+modulePrice(m),0)}
function toggleAddon(a){if(selectedAddon(a))project.modules=project.modules.filter(m=>!a.modules.includes(m));else project.modules=[...new Set([...project.modules,...a.modules])];sync();renderAddons();renderSummary();loadPreview();save()}
function setSingle(key,value){project.hospitality[key]=value;sync();renderWorkflowStates();renderSummary();loadPreview();save()}
function toggleChannel(value){const list=Array.isArray(project.hospitality.channels)?project.hospitality.channels:[];project.hospitality.channels=list.includes(value)?list.filter(x=>x!==value):[...list,value];sync();renderWorkflowStates();renderSummary();loadPreview();save()}
function sync(){project.modules=[...new Set([...STANDARD_MODULES,...project.modules.filter(id=>!STANDARD_MODULES.includes(id))])];project.delivery.packagePrice=STANDARD_BASE;project.delivery.implementationSelected=true;project.delivery.implementationPrice=150;project.delivery.managedServiceSelected=false;project.delivery.managedServicePrice=0;project.company.industry='B&B · Affittacamere · Case vacanza';project.company.slug=G.slugify(project.company.name||'struttura');project.hospitality.unitCount=Math.max(1,Number(project.hospitality.unitCount||1));project.pricing.enabled=project.modules.includes('dynamic_pricing');project.pricing.mode=project.pricing.enabled?'dynamic':'none'}
function profileText(){const type=project.hospitality.type||'Struttura';const units=project.hospitality.unitCount||1;const city=project.hospitality.city?` · ${project.hospitality.city}`:'';return `${type} · ${units} ${units===1?'alloggio':'alloggi'}${city}`}
function renderTypes(){const types=[['B&B','Camere e ospitalità gestite direttamente'],['Affittacamere','Più camere o unità indipendenti'],['Casa vacanza','Uno o più appartamenti o case']];$('#typeGrid').innerHTML=types.map(([t,d])=>`<button class="choice ${project.hospitality.type===t?'active':''}" data-type="${esc(t)}"><b>${esc(t)}</b><span>${esc(d)}</span></button>`).join('');$$('[data-type]').forEach(b=>b.onclick=()=>{project.hospitality.type=b.dataset.type;renderTypes();renderSummary();loadPreview();save()})}
const workflowDefs=[
 {title:'Prenotazioni',desc:'Da dove arrivano oggi?',type:'multi',key:'channels',opts:[['booking','Booking.com'],['airbnb','Airbnb'],['direct','Dirette / telefono'],['other','Altri portali']]},
 {title:'Volume',desc:'Quante prenotazioni gestisci in un mese?',key:'bookingVolume',opts:[['low','Fino a 15'],['medium','15–40'],['high','40+']]},
 {title:'Team',desc:'Quante persone usano o useranno il gestionale?',key:'teamSize',opts:[['solo','Solo io'],['small','2–3'],['large','4+']]},
 {title:'Check-in',desc:'Come accogli gli ospiti?',key:'checkinMode',opts:[['in_person','In presenza'],['mixed','Misto'],['self','Self check-in']]},
 {title:'Pulizie',desc:'Come vengono gestite?',key:'cleaningMode',opts:[['internal','Internamente'],['external','Esternamente'],['mixed','Miste']]},
 {title:'Strumento attuale',desc:'Dove tieni oggi prenotazioni e operazioni?',key:'currentTool',opts:[['manual','Agenda / messaggi'],['sheets','Excel / Fogli'],['pms','Altro gestionale']]}
];
function renderWorkflow(){if(!project.hospitality.channels)project.hospitality.channels=['booking','direct'];if(!project.hospitality.bookingVolume)project.hospitality.bookingVolume='medium';if(!project.hospitality.teamSize)project.hospitality.teamSize='solo';if(!project.hospitality.checkinMode)project.hospitality.checkinMode='in_person';if(!project.hospitality.cleaningMode)project.hospitality.cleaningMode='internal';if(!project.hospitality.currentTool)project.hospitality.currentTool='manual';$('#workGrid').innerHTML=workflowDefs.map((d,i)=>`<article class="work-card" data-work="${i}"><h3>${esc(d.title)}</h3><p>${esc(d.desc)}</p><div class="segmented">${d.opts.map(([v,l])=>`<button class="pill" data-work-opt="${i}:${esc(v)}">${esc(l)}</button>`).join('')}</div></article>`).join('');$$('[data-work-opt]').forEach(b=>b.onclick=()=>{const [i,v]=b.dataset.workOpt.split(':');const d=workflowDefs[Number(i)];d.type==='multi'?toggleChannel(v):setSingle(d.key,v)});renderWorkflowStates()}
function renderWorkflowStates(){workflowDefs.forEach((d,i)=>{const current=d.type==='multi'?(project.hospitality.channels||[]):project.hospitality[d.key];$$(`[data-work-opt^="${i}:"]`).forEach(b=>{const v=b.dataset.workOpt.split(':')[1];b.classList.toggle('active',Array.isArray(current)?current.includes(v):current===v)})})}
function renderAddons(){$('#addonGrid').innerHTML=ADDONS.map((a,i)=>`<button class="addon ${selectedAddon(a)?'active':''}" data-addon="${i}"><div><h3>${esc(a.title)}</h3><p>${esc(a.desc)}</p><span class="switch"><i></i></span></div><div class="addon-price"><strong>+${money(addonListPrice(a))}</strong><span>una tantum</span></div></button>`).join('');$$('[data-addon]').forEach(b=>b.onclick=()=>toggleAddon(ADDONS[Number(b.dataset.addon)]))}
function previewProject(){sync();const p=JSON.parse(JSON.stringify(project));p.entities=G.buildEntities(p);p.delivery.previewApproved=true;return p}
function loadPreview(){const f=$('#productPreview');try{f.srcdoc=T.previewHtml(previewProject())}catch(e){f.srcdoc=`<div style="font:16px Arial;padding:40px">Anteprima non disponibile: ${esc(e.message)}</div>`}}
function renderSummary(){sync();const price=G.calculatePrice(project);const optional=Math.max(0,price.total-150-199);$('#summaryName').textContent=project.company.name||'Easy Come Hospitality';$('#summaryProfile').textContent=profileText();$('#summaryExtras').textContent=money(optional);$('#summaryTotal').textContent=money(price.total);const dr=$('#discountRow');if(price.bundleDiscount>0){dr.style.display='flex';$('#summaryDiscount').textContent='−'+money(price.bundleDiscount)}else dr.style.display='none'}
function bindInputs(){const name=$('#companyName'),city=$('#city'),units=$('#unitCount');name.value=project.company.name||'';city.value=project.hospitality.city||'';units.value=project.hospitality.unitCount||4;name.oninput=()=>{project.company.name=name.value;renderSummary();save()};city.oninput=()=>{project.hospitality.city=city.value;renderSummary();save()};units.onchange=()=>{project.hospitality.unitCount=Math.max(1,Number(units.value||1));renderSummary();loadPreview();save()}}
function setPreviewMode(mode){previewMode=mode;$('#previewWrap').classList.toggle('mobile',mode==='mobile');$$('[data-device]').forEach(b=>b.classList.toggle('active',b.dataset.device===mode))}
function openCheckout(){sync();const price=G.calculatePrice(project),optional=Math.max(0,price.total-150-199),root=$('#checkoutRoot');root.innerHTML=`<div class="checkout-overlay"><section class="checkout"><div class="checkout-left"><button id="closeCheckout" class="checkout-close">×</button><span class="eyebrow">ORDINE EASY COME</span><h2>${esc(project.company.name||'La tua struttura')}</h2><p style="font-size:14px;line-height:1.55;color:#ffffff9a">Stai acquistando Easy Come Hospitality standard con gli extra scelti e l’implementazione obbligatoria.</p><div class="sum-line"><span>Standard</span><strong>€199</strong></div><div class="sum-line"><span>Extra</span><strong>${money(optional)}</strong></div><div class="sum-line"><span>Implementazione</span><strong>€150</strong></div><div class="sum-total"><span>TOTALE UNA TANTUM</span><strong>${money(price.total)}</strong><small>Nessun canone Easy Come obbligatorio.</small></div></div><div class="checkout-right"><span class="eyebrow">DATI ORDINE</span><h3>Completiamo l’acquisto.</h3><form id="checkoutForm"><div class="fields"><div class="field"><label>Nome e cognome</label><input name="customerName" required></div><div class="field"><label>Email</label><input name="email" type="email" required value="${esc(project.company.email||'')}"></div><div class="field full"><label>Struttura / ragione sociale</label><input name="companyName" required value="${esc(project.company.name||'')}"></div></div><label class="legal"><input type="checkbox" name="terms" required><span>Accetto i <a href="${esc(SALES.termsUrl||'/termini')}" target="_blank">Termini</a> e ho letto la <a href="${esc(SALES.privacyUrl||'/privacy')}" target="_blank">Privacy Policy</a>.</span></label><label class="legal"><input type="checkbox" name="immediatePerformance" required><span>Chiedo che l’implementazione inizi dopo il pagamento.</span></label><div id="checkoutError"></div><button class="buy" id="payButton" type="submit">Continua al pagamento · ${money(price.total)}</button></form></div></section></div>`;$('#closeCheckout').onclick=()=>root.innerHTML='';$('#checkoutForm').onsubmit=submitCheckout}
async function submitCheckout(e){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const customer=Object.fromEntries(new FormData(form)),btn=$('#payButton'),err=$('#checkoutError');project.company.name=String(customer.companyName||project.company.name||'').trim();project.company.slug=G.slugify(project.company.name);project.company.email=String(customer.email||'').trim();project.delivery.previewApproved=true;sync();save();const audit=G.auditProject(project);if(!audit.ready){err.innerHTML=`<div class="error">${esc(audit.blockers[0]||'Completa i dati.')}</div>`;return}btn.disabled=true;try{const token=await window.EasyComeAccount?.getAccessToken?.();if(!token){save();const next=`/studio.html${DEMO_SLUG?`?demo=${encodeURIComponent(DEMO_SLUG)}`:''}`;location.href=`/accedi.html?mode=login&next=${encodeURIComponent(next)}`;return}const response=await fetch(SALES.checkoutEndpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({project:{...project,delivery:{...project.delivery,previewApproved:true}},customer,legal:{termsAccepted:customer.terms==='on',immediatePerformance:customer.immediatePerformance==='on',termsVersion:'EC-TOS-HOSPITALITY-V8',acceptedAt:new Date().toISOString()},sourceUrl:location.href})});const d=await response.json().catch(()=>({}));if(!response.ok||!d.url)throw new Error(d.error||'Impossibile avviare il pagamento.');location.href=d.url}catch(e2){err.innerHTML=`<div class="error">${esc(e2.message||String(e2))}</div>`;btn.disabled=false}}
async function loadDemo(){if(!DEMO_SLUG)return null;try{const r=await fetch(`/api/demo-public?slug=${encodeURIComponent(DEMO_SLUG)}`,{cache:'no-store'});const d=await r.json();if(!r.ok||!d.project)return null;demoPayload=d;return d.project}catch(_){return null}}
function applyDemoMode(){if(!DEMO_MODE)return;$('#heroEyebrow').textContent='PERSONALIZZA LA DEMO CHE HAI APPENA PROVATO';$('#heroTitle').innerHTML='Questa è già la tua demo.<br><em>Ora rendila reale.</em>';$('#heroText').textContent='Abbiamo precompilato ciò che sappiamo della struttura. Correggi i dati, raccontaci come lavori e aggiungi soltanto ciò che manca.';$('#demoNote').classList.remove('hidden');$('#prefillNote').classList.remove('hidden');$('#demoBusiness').textContent=project.company.name||demoPayload?.place?.name||'La tua struttura'}
async function init(){const demo=await loadDemo();const inlinePrefill=window.EASYCOME_PREFILL_PROJECT||null;project=normalize(demo||inlinePrefill||localDraft()||G.defaultProject());if(!project.company.name&&!DEMO_SLUG)project.company.name='';renderTypes();bindInputs();renderWorkflow();renderAddons();renderSummary();applyDemoMode();loadPreview();$('#reloadPreview').onclick=loadPreview;$$('[data-device]').forEach(b=>b.onclick=()=>setPreviewMode(b.dataset.device));$('#buy').onclick=openCheckout;$('#buyTop').onclick=openCheckout;$('#save').onclick=()=>{save();$('#save').textContent='Salvato';setTimeout(()=>$('#save').textContent='Salva e continua più tardi',1200)};$('#saveTop').onclick=()=>{save();$('#saveTop').textContent='Salvato';setTimeout(()=>$('#saveTop').textContent='Salva',1000)}}
window.addEventListener('easycome:account-ready',()=>{if(!project)init()});setTimeout(()=>{if(!project)init()},250);
})();
