(function(){
'use strict';
const G=window.ECGenerator;
const T=window.ECHospitalityTemplates;
const SALES=window.EASYCOME_SALES||{mode:'customer',checkoutEndpoint:'/api/create-checkout-session',termsUrl:'/termini',privacyUrl:'/privacy'};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const money=v=>new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v||0));
const DEMO_SLUG=new URLSearchParams(location.search).get('demo')||'';
const STEPS=[
 {label:'La struttura',sub:'30 secondi'},
 {label:'Cosa ti serve',sub:'Solo ciò che serve'},
 {label:'Prova Easy Come',sub:'È il prodotto vero'},
 {label:'Il pacchetto',sub:'Prezzo chiaro'}
];
const CHANNELS=[['booking','Booking.com'],['airbnb','Airbnb'],['direct','Dirette / telefono'],['other','Altri portali']];
const FEATURES=[
 {id:'audit',title:'Controllo automatico',question:'Voglio che Easy Come mi avvisi quando qualcosa non torna',desc:'Sovrapposizioni, saldi aperti, dati ospite mancanti e attività dimenticate.',tag:'MENO ERRORI'},
 {ids:['finance','expenses'],title:'Costi e margini',question:'Voglio capire non solo quanto incasso, ma quanto mi resta',desc:'Costi, fornitori, commissioni e differenza gestionale dentro Numeri.',tag:'PIÙ CONTROLLO'},
 {id:'channel_sync',title:'Calendari dei portali',question:'Ricevo prenotazioni da più portali',desc:'Ordine sui calendari esterni e stato delle connessioni nella stessa app.',tag:'NO DOPPIE PRENOTAZIONI'},
 {ids:['guest_comms','self_checkin'],title:'Accoglienza ospiti',question:'Voglio perdere meno tempo prima del check-in',desc:'Dati pre-arrivo, documenti, messaggi e checklist collegati al soggiorno.',tag:'MENO MESSAGGI'},
 {id:'tourist_tax',title:'Tassa di soggiorno',question:'Voglio tenere ordinati importi, esenzioni e rendicontazione',desc:'La tassa resta collegata alla prenotazione corretta e compare negli adempimenti.',tag:'ADEMPIMENTI'},
 {id:'dynamic_pricing',title:'Tariffe e regole',question:'Voglio gestire meglio stagioni, minimi e prezzi',desc:'Regole di prezzo e soggiorno configurate durante l’implementazione.',tag:'RICAVI'},
 {id:'multiuser',title:'Team e permessi',question:'Easy Come lo userà anche qualcun altro',desc:'Accessi e responsabilità separati per titolare, reception e pulizie.',tag:'TEAM'},
 {id:'automations',title:'Automazioni',question:'Voglio che le attività ripetitive partano da sole',desc:'Routine su prenotazioni, arrivi, partenze, messaggi, incassi e pulizie.',tag:'TEMPO'}
];
let activeUserId='guest',currentStep=0,project=normalize(G.defaultProject());

function featureIds(f){return f.ids||[f.id]}
function featureActive(f){return featureIds(f).every(id=>project.modules.includes(id))}
function modulePrice(id){return Number(G.MODULES.find(m=>m.id===id)?.price||0)}
function featurePrice(f){return featureIds(f).reduce((s,id)=>s+modulePrice(id),0)}
function selectedFeatures(){return FEATURES.filter(featureActive)}
function normalize(input){const base=G.defaultProject(),p={...base,...(input||{}),company:{...base.company,...(input?.company||{})},pricing:{...base.pricing,...(input?.pricing||{})},delivery:{...base.delivery,...(input?.delivery||{})}};const allowed=new Set(['hospitality_core','reports','easycome_hub',...FEATURES.flatMap(featureIds)]);p.modules=[...new Set([...(p.modules||[]).filter(id=>allowed.has(id)),'hospitality_core','reports','easycome_hub'])];p.customEntities=[];const h=p.hospitality||{},count=Math.max(1,Number(h.unitCount||h.unitTypes?.reduce((s,u)=>s+Number(u.count||1),0)||4));p.hospitality={...h,type:h.type||'B&B',city:h.city||'',unitCount:count,channels:Array.isArray(h.channels)?h.channels:['booking','direct'],teamSize:h.teamSize||'solo',unitTypes:[{name:'Camera / alloggio',count,capacity:2,basePrice:Number(h.unitTypes?.[0]?.basePrice||95)}],checkinFrom:h.checkinFrom||'15:00',checkoutBy:h.checkoutBy||'10:30'};p.templateId='hospitality';p.company.industry='Ospitalità indipendente';p.delivery.implementationSelected=true;p.delivery.implementationPrice=150;p.delivery.managedServiceSelected=false;p.delivery.managedServicePrice=0;syncProject(p);return p}
function syncProject(p=project){const h=p.hospitality,count=Math.max(1,Number(h.unitCount||1));h.unitTypes=[{name:'Camera / alloggio',count,capacity:2,basePrice:Number(h.unitTypes?.[0]?.basePrice||95)}];h.maxGuests=Math.max(2,count*2);p.company.description=`Easy Come Hospitality per ${h.type||'struttura ricettiva'} con ${count} camere o alloggi.`;p.pricing.mode='none';p.pricing.enabled=false;p.delivery.implementationSelected=true;p.delivery.implementationPrice=150;p.delivery.managedServiceSelected=false;p.delivery.managedServicePrice=0}
function save(){syncProject();try{localStorage.setItem(draftKey(),JSON.stringify(project))}catch(_){}window.EasyComeAccount?.saveProject?.(project)}
function draftKey(){return `easycome-hospitality-v3:${activeUserId||'guest'}`}
function localDraft(){try{return JSON.parse(localStorage.getItem(draftKey())||'null')}catch(_){return null}}
function setFeature(f,on){featureIds(f).forEach(id=>{project.modules=project.modules.filter(x=>x!==id);if(on)project.modules.push(id)});project.modules=[...new Set(project.modules)];project.delivery.previewApproved=false;save();render()}
function toast(text){const n=document.createElement('div');n.className='toast';n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),1700)}
function heading(k,title,desc){return `<div class="heading"><div><span class="eyebrow">${k}</span><h1>${title}</h1><p>${desc}</p></div><span class="step-count">${currentStep+1} / ${STEPS.length}</span></div>`}
function recommended(){const h=project.hospitality,rec=new Set(['audit']);if((h.channels||[]).filter(x=>x!=='direct').length>=1)rec.add('channel_sync');if(Number(h.unitCount||0)>=3){rec.add('guest_comms');rec.add('self_checkin')}if(Number(h.unitCount||0)>=5)rec.add('automations');if(h.teamSize!=='solo')rec.add('multiuser');return rec}
function recommendationText(){const r=recommended(),labels=[];FEATURES.forEach(f=>{if(featureIds(f).some(id=>r.has(id)))labels.push(f.title)});return labels.slice(0,4)}
const CORE_MODULES=['hospitality_core','reports','easycome_hub'];
function presetModules(mode){if(mode==='base')return [...CORE_MODULES];if(mode==='full')return [...new Set([...CORE_MODULES,...FEATURES.flatMap(featureIds)])];const r=recommended();return [...new Set([...CORE_MODULES,...FEATURES.filter(f=>featureIds(f).some(id=>r.has(id))).flatMap(featureIds)])]}
function presetPrice(mode){const clone=JSON.parse(JSON.stringify(project));clone.modules=presetModules(mode);return G.calculatePrice(clone).total}
function applyPreset(mode){project.modules=presetModules(mode);project.delivery.previewApproved=false;save();render();toast(mode==='base'?'Partenza essenziale applicata':mode==='full'?'Configurazione completa applicata':'Configurazione consigliata applicata')}
function render(){syncProject();document.body.classList.toggle('previewing',currentStep===2);renderSteps();$('#panel').innerHTML=[stepStructure,stepNeeds,stepPreview,stepPrice][currentStep]();renderSummary();updateNav();bindCurrent();save()}
function renderSteps(){$('#stepList').innerHTML=STEPS.map((s,i)=>`<button class="step-tab ${i===currentStep?'active':''}" data-step="${i}"><small>0${i+1}</small><span><strong>${s.label}</strong><em>${s.sub}</em></span></button>`).join('');$$('[data-step]').forEach(b=>b.onclick=()=>{currentStep=Number(b.dataset.step);render();scrollTo(0,0)})}

function stepStructure(){const h=project.hospitality,c=project.company;return `${heading('PARTIAMO DA TE','Che struttura gestisci?','Bastano poche informazioni. Tutto ciò che è tecnico lo configuriamo noi durante l’implementazione.')}
<section class="card setup-card"><div class="section-title"><h2>La tua struttura</h2><p>Niente questionario infinito.</p></div><div class="types">${['B&B','Affittacamere','Casa vacanza'].map(v=>`<button class="type-btn ${h.type===v?'active':''}" data-type="${v}"><b>${v}</b><small>${v==='B&B'?'Camere e ospitalità gestite direttamente':v==='Affittacamere'?'Più camere o unità indipendenti':'Uno o più appartamenti / case'}</small></button>`).join('')}</div><div class="fields"><label class="field wide"><span>Nome della struttura</span><input id="companyName" value="${esc(c.name||'')}" placeholder="Es. Dimora Aurora"></label><label class="field"><span>Città</span><input id="city" value="${esc(h.city||'')}" placeholder="Es. Roma"></label><label class="field"><span>Camere / alloggi</span><input id="unitCount" type="number" min="1" max="100" value="${Number(h.unitCount||4)}"></label></div></section>
<section class="card compact-card"><div class="split-title"><div><span class="eyebrow">PRENOTAZIONI</span><h2>Da dove arrivano oggi?</h2></div><p>Serve solo per consigliarti la configurazione giusta.</p></div><div class="choice-row">${CHANNELS.map(([id,l])=>`<button data-channel="${id}" class="choice ${h.channels.includes(id)?'active':''}"><span>${l}</span></button>`).join('')}</div></section>
<section class="card compact-card"><div class="split-title"><div><span class="eyebrow">TEAM</span><h2>Chi userà Easy Come?</h2></div></div><div class="choice-row team">${[['solo','Solo io'],['small','Siamo in 2–3'],['team','Siamo 4+']].map(([id,l])=>`<button data-team="${id}" class="choice ${h.teamSize===id?'active':''}">${l}</button>`).join('')}</div></section>`}

function stepNeeds(){const rec=recommendationText();return `${heading('PERSONALIZZA SENZA COMPLICARTI','Come vuoi partire?','Puoi scegliere una configurazione pronta in un clic oppure rifinire le singole funzioni sotto. La gestione quotidiana è sempre inclusa.')}
<section class="preset-box"><div class="preset-copy"><span>SCELTA RAPIDA</span><h2>Tre modi per partire. Nessuna scelta sbagliata.</h2><p>Per ${Number(project.hospitality.unitCount||1)} camere/alloggi ti suggeriamo: <b>${rec.length?rec.join(' · '):'Essenziale'}</b>.</p></div><div class="preset-row"><button data-preset="base"><small>SEMPLICE</small><b>Essenziale</b><span>Gestionale completo, senza extra.</span><strong>${money(presetPrice('base'))}</strong></button><button data-preset="recommended" class="recommended"><small>PER LA TUA STRUTTURA</small><b>Consigliato</b><span>Attiva solo ciò che ha senso per come lavori.</span><strong>${money(presetPrice('recommended'))}</strong></button><button data-preset="full"><small>TUTTO ATTIVO</small><b>Completo</b><span>Tutte le capacità Hospitality disponibili.</span><strong>${money(presetPrice('full'))}</strong></button></div></section>
<div class="included-strip"><b>Sempre incluso</b><span>Oggi</span><span>Calendario</span><span>Prenotazioni</span><span>Operazioni</span><span>Numeri base</span><span>Dati ospiti</span></div>
<div class="fine-title"><div><span class="eyebrow">SE VUOI RIFINIRLO</span><h2>Scegli cosa deve fare in più.</h2></div><p>Clicca soltanto le cose che vuoi. Non nasceranno nuovi menu: potenziano le 5 aree che hai già visto.</p></div><section class="feature-grid">${FEATURES.map((f,i)=>`<button type="button" class="feature ${featureActive(f)?'active':''}" data-feature="${i}"><div class="feature-top"><span>${f.tag}</span><i>${featureActive(f)?'Attivo':'Aggiungi'}</i></div><h3>${f.question}</h3><p>${f.desc}</p><footer><b>${f.title}</b><strong>+${money(featurePrice(f))}</strong></footer></button>`).join('')}</section><div class="note"><b>Il cliente non deve fare il lavoro del tecnico.</b><p>Camere, tariffe, regole, utenti, import dei dati e messa a punto vengono definiti con noi durante l’implementazione obbligatoria. Qui devi solo scegliere il risultato che vuoi.</p></div>`}

function previewProject(){syncProject();const p=JSON.parse(JSON.stringify(project));p.company.name=p.company.name||'La tua struttura';p.organizationId=`pv-${G.slugify(p.company.name)||'easycome'}-${p.hospitality.unitCount}-${p.modules.length}`;p.entities=G.buildEntities(p);return p}
function stepPreview(){return `${heading('PROVALO DAVVERO','Questo è il gestionale che ricevi.','Non è un mockup. È la stessa applicazione generata da Easy Come: puoi navigare, aprire prenotazioni e provare i flussi.')}
<section class="live-preview"><div class="live-toolbar"><div><span class="live-dot"></span><b>ANTEPRIMA LIVE</b><small>Clicca tutto. È il prodotto vero.</small></div><div><button id="reloadPreview">Ripristina</button><button id="expandPreview" class="dark">Schermo intero</button></div></div>${previewFallbackMarkup()}<iframe id="productPreview" title="Anteprima Easy Come Hospitality"></iframe></section><div class="preview-promise"><span>STESSA INTERFACCIA</span><h3>Quello che provi qui è quello che userai.</h3><p>Oggi, Calendario, Prenotazioni, Operazioni e Numeri restano identici nel prodotto consegnato. Le funzioni che acquisti potenziano queste aree senza creare nuovi menu inutili.</p></div>`}

function stepPrice(){const price=G.calculatePrice(project),sel=selectedFeatures();return `${heading('IL TUO PACCHETTO','Sai esattamente cosa compri.','Un acquisto una tantum. Il prezzo del software dipende solo dalle capacità che hai scelto; l’implementazione da €150 è obbligatoria.')}
<section class="checkout-preview"><div class="package-main"><span class="eyebrow">EASY COME HOSPITALITY</span><h2>${esc(project.company.name||'La tua struttura')}</h2><p>${esc(project.hospitality.type)} · ${Number(project.hospitality.unitCount||1)} camere/alloggi</p><div class="package-lines"><div><span>Gestionale Hospitality</span><b>${money(price.base)}</b></div>${sel.map(f=>`<div><span>${esc(f.title)}</span><b>+${money(featurePrice(f))}</b></div>`).join('')}<div><span>Implementazione e messa a punto</span><b>${money(price.implementation)}</b></div></div><div class="package-total"><span>TOTALE UNA TANTUM</span><strong>${money(price.total)}</strong><small>Nessun canone Easy Come obbligatorio.</small></div><button id="buy" class="buy">Acquista Easy Come</button></div><aside class="implementation"><span class="eyebrow">I €150 SERVONO A QUESTO</span><h3>Non ti lasciamo un software da configurare.</h3><ol><li><b>Capire il tuo flusso reale</b><span>Camere, canali, check-in, pagamenti, pulizie.</span></li><li><b>Configurare Easy Come</b><span>Regole, utenti, tariffe e dati iniziali.</span></li><li><b>Testare i passaggi importanti</b><span>Prenotazione, arrivo, saldo, pulizia, adempimenti.</span></li><li><b>Consegnarlo pronto</b><span>Tu apri Easy Come e inizi a lavorare.</span></li></ol></aside></section>`}

function renderSummary(){const h=project.hospitality,p=G.calculatePrice(project),sel=selectedFeatures();$('#summary').innerHTML=`<div class="summary-title"><small>IL TUO EASY COME</small><h2>${esc(project.company.name||'La tua struttura')}</h2><p>${esc(h.type)} · ${Number(h.unitCount||1)} camere/alloggi</p></div><div class="summary-core"><span>SEMPRE INCLUSO</span><p>Oggi · Calendario · Prenotazioni · Operazioni · Numeri</p></div>${sel.length?`<div class="summary-selected"><span>AGGIUNTE</span>${sel.map(f=>`<div><b>${esc(f.title)}</b><em>+${money(featurePrice(f))}</em></div>`).join('')}</div>`:''}<div class="summary-total"><span>TOTALE CON IMPLEMENTAZIONE</span><strong>${money(p.total)}</strong><small>una tantum</small></div>`}
function updateNav(){const prev=$('#previous'),next=$('#next');prev.disabled=currentStep===0;next.textContent=currentStep===3?'Torna alle funzioni':currentStep===2?'Vedi il prezzo':'Continua';$('#progressMobile').textContent=`${currentStep+1} / ${STEPS.length}`}
function bindInput(id,fn){const el=$('#'+id);if(!el)return;el.oninput=()=>{fn(el.value);project.delivery.previewApproved=false;save();renderSummary()}}
function previewFallbackMarkup(){return `<div class="preview-fallback" id="previewFallback"><section class="preview-fallback-card"><aside class="pf-side"><div class="pf-brand">Easy Come</div>${['Oggi','Calendario','Prenotazioni','Operazioni','Numeri'].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join('')}</aside><main class="pf-main"><span>ANTEPRIMA</span><h3>Oggi, tutto sotto controllo.</h3><div class="pf-kpis"><div><small>ARRIVI</small><b>3</b></div><div><small>PARTENZE</small><b>2</b></div><div><small>DA INCASSARE</small><b>€640</b></div></div><div class="pf-list"><div><b>14:30 · Giulia Romano</b><span>Camera 1</span></div><div><b>16:00 · Marco De Luca</b><span>Saldo €290</span></div><div><b>Prima dell’arrivo · Camera 3</b><span>Da preparare</span></div></div></main></section></div>`}
function loadPreview(iframe=$('#productPreview')){if(!iframe)return;const fallback=$('#previewFallback');if(fallback)fallback.classList.remove('hidden');if(!T?.previewHtml){iframe.style.display='none';return}try{const html=T.previewHtml(previewProject());iframe.onload=()=>{iframe.style.display='block';fallback?.classList.add('hidden')};iframe.srcdoc=html;setTimeout(()=>{try{if(iframe.contentDocument?.getElementById('hospitalityApp')?.children.length){iframe.style.display='block';fallback?.classList.add('hidden')}}catch(_){}},700)}catch(_){iframe.style.display='none'}}
function expandPreview(){const host=$('#previewOverlay');host.innerHTML=`<div class="preview-overlay"><section><header><div><b>Easy Come Hospitality · Anteprima live</b><span>È la stessa interfaccia del prodotto finale</span></div><button id="closeBigPreview">×</button></header><iframe id="bigProductPreview"></iframe></section></div>`;const frame=$('#bigProductPreview');try{frame.srcdoc=T.previewHtml(previewProject())}catch(_){frame.outerHTML='<div class="preview-unavailable">Anteprima non disponibile in questo browser. Torna alla vista integrata.</div>'}$('#closeBigPreview').onclick=()=>host.innerHTML=''}
function bindCurrent(){if(currentStep===0){$$('[data-type]').forEach(b=>b.onclick=()=>{project.hospitality.type=b.dataset.type;render()});$$('[data-channel]').forEach(b=>b.onclick=()=>{const id=b.dataset.channel,a=new Set(project.hospitality.channels||[]);a.has(id)?a.delete(id):a.add(id);project.hospitality.channels=[...a];render()});$$('[data-team]').forEach(b=>b.onclick=()=>{project.hospitality.teamSize=b.dataset.team;render()});bindInput('companyName',v=>{project.company.name=v;project.company.slug=G.slugify(v)});bindInput('city',v=>project.hospitality.city=v);bindInput('unitCount',v=>project.hospitality.unitCount=Math.max(1,Number(v||1)))}if(currentStep===1){$$('[data-feature]').forEach(b=>b.onclick=()=>{const f=FEATURES[Number(b.dataset.feature)];setFeature(f,!featureActive(f))});$$('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset))}if(currentStep===2){setTimeout(loadPreview,0);$('#reloadPreview')?.addEventListener('click',()=>loadPreview());$('#expandPreview')?.addEventListener('click',expandPreview)}if(currentStep===3)$('#buy')?.addEventListener('click',openCheckout)}
function next(){if(currentStep===3)currentStep=1;else{if(currentStep===2)project.delivery.previewApproved=true;currentStep++}render();scrollTo(0,0)}
function prev(){if(currentStep>0){currentStep--;render();scrollTo(0,0)}}
function projectForCheckout(){syncProject();return {...project,company:{...project.company},delivery:{...project.delivery,previewApproved:true,implementationSelected:true,implementationPrice:150,managedServiceSelected:false,managedServicePrice:0}}}
function openCheckout(){const price=G.calculatePrice(project),root=$('#checkoutRoot');root.innerHTML=`<div class="checkout-overlay"><section class="checkout-sheet"><div class="checkout-copy"><div class="checkout-top"><div><span class="checkout-label">ORDINE EASY COME</span><h2>${esc(project.company.name||'La tua struttura')}</h2><p>Hai già provato il prodotto. Qui servono solo i dati per completare l’ordine.</p></div><button class="checkout-close" id="closeCheckout">×</button></div><div class="order-lines"><div><span>Gestionale Hospitality</span><strong>${money(price.base)}</strong></div>${selectedFeatures().map(f=>`<div><span>${esc(f.title)}</span><strong>+${money(featurePrice(f))}</strong></div>`).join('')}<div><span>Implementazione</span><strong>${money(price.implementation)}</strong></div></div><div class="order-total"><div><span class="checkout-label">TOTALE UNA TANTUM</span><small>Nessun canone Easy Come obbligatorio</small></div><strong>${money(price.total)}</strong></div></div><div class="checkout-form-wrap"><form id="checkoutForm"><span class="eyebrow">DATI ORDINE</span><h3>Completiamo l’acquisto.</h3><div class="fields checkout-fields"><label class="field"><span>Nome e cognome</span><input name="customerName" required></label><label class="field"><span>Email</span><input name="email" type="email" required value="${esc(project.company.email||'')}"></label><label class="field"><span>Telefono</span><input name="phone"></label><label class="field"><span>Partita IVA / CF</span><input name="taxId"></label><label class="field full"><span>Struttura / ragione sociale</span><input name="companyName" required value="${esc(project.company.name||'')}"></label></div><label class="legal-check"><input type="checkbox" name="terms" required><span>Accetto i <a href="${esc(SALES.termsUrl||'/termini')}" target="_blank">Termini e condizioni</a> e ho letto la <a href="${esc(SALES.privacyUrl||'/privacy')}" target="_blank">Privacy Policy</a>.</span></label><label class="legal-check"><input type="checkbox" name="immediatePerformance" required><span>Chiedo che l’implementazione inizi dopo il pagamento.</span></label><div id="checkoutError"></div><button id="payButton" class="buy" type="submit">Continua al pagamento · ${money(price.total)}</button><div class="secure-row">Pagamento gestito tramite Stripe.</div></form></div></section></div>`;$('#closeCheckout').onclick=()=>root.innerHTML='';$('#checkoutForm').onsubmit=submitCheckout}
async function submitCheckout(e){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const customer=Object.fromEntries(new FormData(form)),button=$('#payButton'),error=$('#checkoutError');project.company.name=String(customer.companyName||project.company.name||'').trim();project.company.slug=G.slugify(project.company.name);project.company.email=String(customer.email||'').trim();project.delivery.previewApproved=true;syncProject();save();const audit=G.auditProject(project);if(!audit.ready){error.innerHTML=`<div class="checkout-error">${esc(audit.blockers[0]||'Completa i dati dell’ordine.')}</div>`;return}button.disabled=true;button.textContent='Controllo account…';error.innerHTML='';try{const token=await window.EasyComeAccount?.getAccessToken?.();if(!token){save();location.href=`/accedi.html?mode=login&next=${encodeURIComponent('/studio.html')}`;return}button.textContent='Apertura del pagamento…';const response=await fetch(SALES.checkoutEndpoint,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({project:projectForCheckout(),customer,legal:{termsAccepted:customer.terms==='on',immediatePerformance:customer.immediatePerformance==='on',termsVersion:'EC-TOS-HOSPITALITY-V3',acceptedAt:new Date().toISOString()},sourceUrl:location.href})});const data=await response.json().catch(()=>({}));if(!response.ok||!data.url)throw new Error(data.error||'Impossibile avviare il pagamento.');location.href=data.url}catch(err){error.innerHTML=`<div class="checkout-error">${esc(err.message||String(err))}</div>`;button.disabled=false;button.textContent=`Continua al pagamento · ${money(G.calculatePrice(project).total)}`}}
async function loadDemo(){if(!DEMO_SLUG)return null;try{const r=await fetch(`/api/demo-public?slug=${encodeURIComponent(DEMO_SLUG)}`,{cache:'no-store'}),d=await r.json();if(!r.ok||!d.project)return null;const p=d.project;p.company={...(p.company||{}),email:''};p.delivery={...(p.delivery||{}),previewApproved:false};return p}catch(_){return null}}
async function initialize(user){activeUserId=user?.id||'guest';const demo=await loadDemo(),cloud=demo?null:await window.EasyComeAccount?.loadLatestProject?.(),local=demo?null:localDraft();project=normalize(demo||cloud||local||G.defaultProject());currentStep=demo?1:0;render()}
window.addEventListener('easycome:account-ready',e=>initialize(e.detail?.user));$('#previous').onclick=prev;$('#next').onclick=next;$('#homeLink').onclick=()=>location.href='index.html';setTimeout(()=>{if(!$('#stepList').children.length)initialize(null)},400);
})();
