(function(){
'use strict';
const $=s=>document.querySelector(s),G=window.ECGenerator,T=window.ECHospitalityTemplates;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const slug=new URLSearchParams(location.search).get('d')||new URLSearchParams(location.search).get('demo')||'';
function fail(msg){$('#app').className='';$('#app').innerHTML=`<div class="error"><span>DEMO EASY COME</span><h1>Demo non disponibile.</h1><p>${esc(msg)}</p><a href="/">Torna a Easy Come</a></div>`}
async function track(event){try{await fetch('/api/demo-track',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({slug,event})})}catch(_){}}
async function init(){try{if(!slug)throw new Error('Link demo incompleto.');if(!G||!T)throw new Error('Motore Hospitality non caricato.');const r=await fetch(`/api/demo-public?slug=${encodeURIComponent(slug)}`,{cache:'no-store'});const d=await r.json();if(!r.ok||!d.project)throw new Error(d.error||'Demo non disponibile.');const p=d.project;p.entities=G.buildEntities(p);p.delivery={...(p.delivery||{}),previewApproved:true};document.title=`Easy Come per ${d.place?.name||p.company?.name||'la struttura'}`;const studio=`/studio.html?demo=${encodeURIComponent(slug)}&source=factory`;
$('#app').className='';$('#app').innerHTML=`<main class="demo-page"><header class="demo-bar"><div class="demo-brand"><b>EC</b><div><small>DEMO PREPARATA PER</small><strong>${esc(d.place?.name||p.company?.name||'La tua struttura')}</strong></div></div><div class="demo-context"><span>${esc(d.place?.address||'')}</span><strong>Easy Come Hospitality standard · ${Number(d.price||349).toLocaleString('it-IT',{style:'currency',currency:'EUR',minimumFractionDigits:0})} una tantum</strong></div><a class="demo-cta" id="configure" href="${studio}">Personalizza Easy Come</a></header><section class="product-host"><iframe id="demoFrame" title="Easy Come Hospitality"></iframe></section><footer class="demo-foot"><span>I dati operativi sono dimostrativi. Nome e informazioni pubbliche servono soltanto a personalizzare l’esperienza.</span><span>Prova direttamente il gestionale: ciò che vedi è la stessa interfaccia del prodotto finale.</span></footer></main>`;$('#demoFrame').srcdoc=T.previewHtml(p);$('#configure').onclick=()=>track('cta_configure');track('demo_loaded')}catch(e){fail(e.message)}}
init();
})();
