(function(){'use strict';
  const cfg=window.EASYCOME_LEGAL||{};const consentCfg=cfg.consent||{};
  const key='easycome_consent_v1';const reaskDays=Number(consentCfg.reaskAfterDays||180);const features={analytics:Boolean(consentCfg.analyticsEnabled),marketing:Boolean(consentCfg.marketingEnabled)};const optionalEnabled=Boolean(features.analytics||features.marketing);
  const now=()=>Date.now();const expiryMs=reaskDays*86400000;
  const parse=()=>{try{const v=JSON.parse(localStorage.getItem(key)||'null');if(!v||!v.savedAt||now()-v.savedAt>expiryMs)return null;const old=v.features||{analytics:false,marketing:false};if(old.analytics!==features.analytics||old.marketing!==features.marketing)return null;return v}catch(_){return null}};
  const save=v=>{const data={necessary:true,analytics:features.analytics&&Boolean(v.analytics),marketing:features.marketing&&Boolean(v.marketing),features,savedAt:now(),version:1};try{localStorage.setItem(key,JSON.stringify(data))}catch(_){};apply(data);document.dispatchEvent(new CustomEvent('easycome:consent',{detail:data}));return data};
  const state=()=>parse()||{necessary:true,analytics:false,marketing:false,savedAt:null,version:1};
  function runScripts(category){document.querySelectorAll(`script[type="text/plain"][data-consent-category="${category}"]`).forEach(old=>{if(old.dataset.loaded==='1')return;const s=document.createElement('script');for(const a of old.attributes){if(!['type','data-consent-category','data-src','data-loaded'].includes(a.name))s.setAttribute(a.name,a.value)}if(old.dataset.src)s.src=old.dataset.src;else s.text=old.textContent;old.dataset.loaded='1';old.after(s)})}
  function apply(v){if(v.analytics)runScripts('analytics');if(v.marketing)runScripts('marketing')}
  function backdrop(){const b=document.createElement('div');b.className='ec-consent-backdrop';return b}
  function removeUI(){document.querySelector('.ec-consent-backdrop')?.remove();document.querySelector('.ec-consent-banner')?.remove();document.querySelector('.ec-consent-panel')?.remove()}
  function panel(){removeUI();const v=state();const b=backdrop();const p=document.createElement('section');p.className='ec-consent-panel';p.setAttribute('role','dialog');p.setAttribute('aria-modal','true');p.setAttribute('aria-label','Preferenze privacy');p.innerHTML=`<header><span class="ec-consent-kicker">PRIVACY</span><h2>Scegli cosa autorizzare.</h2><p>Le tecnologie necessarie mantengono accesso, sicurezza e progetto. Analytics e marketing restano spenti finché non li autorizzi.</p></header><div class="ec-consent-choice"><div><strong>Necessari</strong><small>Autenticazione, sicurezza, salvataggio del progetto e memoria delle preferenze. Non possono essere disattivati perché servono a fornire il servizio.</small></div><button type="button" class="ec-consent-switch" aria-checked="true" aria-disabled="true"></button></div><div class="ec-consent-choice"><div><strong>Analytics</strong><small>Misurazione dell'utilizzo del sito. Nella versione attuale Easy Come non carica strumenti analytics non necessari.</small></div><button type="button" class="ec-consent-switch" data-switch="analytics" aria-checked="${features.analytics&&v.analytics?'true':'false'}" aria-disabled="${features.analytics?'false':'true'}"></button></div><div class="ec-consent-choice"><div><strong>Marketing</strong><small>Pixel o tecnologie per pubblicità personalizzata. Nella versione attuale Easy Come non carica strumenti di marketing.</small></div><button type="button" class="ec-consent-switch" data-switch="marketing" aria-checked="${features.marketing&&v.marketing?'true':'false'}" aria-disabled="${features.marketing?'false':'true'}"></button></div><div class="ec-consent-panel-footer"><a href="/cookie">Cookie Policy</a><div><button type="button" data-close>Chiudi</button> <button type="button" class="primary" data-save>Salva preferenze</button></div></div>`;document.body.append(b,p);p.querySelectorAll('[data-switch]').forEach(x=>x.onclick=()=>{if(x.getAttribute('aria-disabled')==='true')return;x.setAttribute('aria-checked',x.getAttribute('aria-checked')==='true'?'false':'true')});p.querySelector('[data-close]').onclick=removeUI;p.querySelector('[data-save]').onclick=()=>{save({analytics:features.analytics&&p.querySelector('[data-switch="analytics"]').getAttribute('aria-checked')==='true',marketing:features.marketing&&p.querySelector('[data-switch="marketing"]').getAttribute('aria-checked')==='true'});removeUI()};b.onclick=removeUI}
  function banner(){removeUI();const b=document.createElement('section');b.className='ec-consent-banner';b.setAttribute('role','dialog');b.setAttribute('aria-label','Preferenze cookie');b.innerHTML=`<div><span class="ec-consent-kicker">PRIVACY, SENZA TRUCCHI</span><h2>Decidi tu cosa possiamo usare.</h2><p>Easy Come usa tecnologie necessarie per accesso e salvataggio. Gli strumenti analytics o marketing, se attivati in futuro, resteranno bloccati finché non scegli di accettarli.</p></div><div class="ec-consent-actions"><a href="/cookie">Dettagli</a><button data-custom>Personalizza</button><button data-reject>Solo necessari</button><button class="accent" data-accept>Accetta tutti</button></div>`;document.body.append(b);b.querySelector('[data-custom]').onclick=panel;b.querySelector('[data-reject]').onclick=()=>{save({analytics:false,marketing:false});removeUI()};b.querySelector('[data-accept]').onclick=()=>{save({analytics:features.analytics,marketing:features.marketing});removeUI()}}
  function trigger(){if(!optionalEnabled)return;const t=document.createElement('button');t.className='ec-cookie-trigger';t.type='button';t.textContent='Privacy';t.setAttribute('aria-label','Modifica preferenze privacy');t.onclick=panel;document.body.append(t)}
  window.EasyComeConsent={get:state,open:panel,save,has:c=>Boolean(state()[c])};
  document.addEventListener('DOMContentLoaded',()=>{const v=parse();if(v)apply(v);if(optionalEnabled&&!v)banner();trigger();document.querySelectorAll('[data-open-cookie-settings]').forEach(x=>x.addEventListener('click',e=>{e.preventDefault();panel()}))});
})();
